{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c839727c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver as wd\n",
    "from selenium.webdriver import ActionChains\n",
    "import chromedriver_binary\n",
    "import time\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def bestbuyLogin():\n",
    "    email = wd.find_element_by_xpath('//*[@id=\"fld-e\"]')   \n",
    "    type(email)\n",
    "    email.send_keys(\"_______\") #Enter Email\n",
    "\n",
    "    acctpassword = wd.find_element_by_xpath('//*[@id=\"fld-p1\"]')   \n",
    "    type(acctpassword)\n",
    "    acctpassword.send_keys(\"______\") #Enter Password\n",
    "\n",
    "    signin = wd.find_element_by_class_name(\"c-button-icon-leading\")\n",
    "    signin.click()\n",
    "    \n",
    "\n",
    "def exitBestbuyPopup():\n",
    "    try:\n",
    "        time.sleep(5)\n",
    "        popupX = wd.find_element_by_class_name('c-close-icon')\n",
    "        popupX.click()\n",
    "    \n",
    "    except:\n",
    "        time.sleep(5)\n",
    "        \n",
    "\n",
    "def checkoutInstructionsBESTBUY():\n",
    "    time.sleep(5)\n",
    "    wd.get(\"https://www.bestbuy.com/cart\")\n",
    "\n",
    "    go_to_checkout = wd.find_element_by_class_name('btn-primary')\n",
    "    go_to_checkout.click()\n",
    "    \n",
    "    time.sleep(2)\n",
    "    bestbuyLogin()\n",
    "\n",
    "    time.sleep(4)\n",
    "    security_code_input = wd.find_element_by_xpath('//*[@id=\"credit-card-cvv\"]')\n",
    "    type(security_code_input)\n",
    "\n",
    "    security_code_input.send_keys(\"___\") #put in for last step\n",
    "\n",
    "    Place_order_btn = wd.find_element_by_xpath('//*[@id=\"checkoutApp\"]/div[2]/div[1]/div[1]/main/div[2]/div[2]/div/div[5]/div[3]/div/div[2]/button')\n",
    "\n",
    "    Place_order_btn.click()\n",
    "        \n",
    "        \n",
    "\n",
    "\n",
    "def CheckBuyButton():\n",
    "    check = False\n",
    "\n",
    "    while not check:\n",
    "    \n",
    "        if(wd.find_element_by_class_name(\"add-to-cart-button\").is_enabled()):\n",
    "            addToCartBtn = wd.find_element_by_class_name(\"add-to-cart-button\")\n",
    "            check = True\n",
    "        else:\n",
    "            wd.refresh()\n",
    "        \n",
    "    print(\"in stock\")\n",
    "    addToCartBtn.click()     \n",
    "    \n",
    "    \n",
    "wd.get('') #put in bestbuy product page you want to use the bot on\n",
    "\n",
    "CheckBuyButton()\n",
    "\n",
    "checkoutInstructionsBESTBUY()\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
